### ISSUE TITLE
gradio_app.py crashes after image and question submit

### ISSUE THREAD

**Issue by zoldaten** [infinigence/Infini-Megrez-Omni#4]
```
Traceback (most recent call last):
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\gradio\blocks.py", line 1532, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\gradio\utils.py", line 671, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\gradio\utils.py", line 664, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\gradio\utils.py", line 647, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\gradio\utils.py", line 809, in gen_wrapper
    response = next(iterator)
  File "C:\Users\user\Desktop\2\Infini-Megrez-Omni\gradio_app.py", line 147, in bot
    for subtext in iterable_streamer:
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\transformers\generation\streamers.py", line 223, in __next__
    value = self.text_queue.get(timeout=self.timeout)
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.9.10\lib\queue.py", line 179, in get
    raise Empty
_queue.Empty
```

**Comment by lizhiyuanUSTC** [comment]
Are you using a GPU to infer the model? According to the logs you provided, the model inference has timed out. You may try increasing the value of the timeout [here](https://github.com/infinigence/Infini-Megrez-Omni/blob/main/gradio_app.py#L44).

**Comment by zoldaten** [comment]
thanks! that fixed the issue. i put 60 sec as timeout.
